@extends('layouts.content')
@section('content')
<div class="container-fluid bg-d  pb-5">

<section>
    <div class="container">
        <div class="row text-center text-white py-3">
        <h3 class="pt-5 pb-1" style="font-family: 'Architects Daughter';font-style: normal;font-weight: 400;font-size: 60px;line-height: 83px;text-align: center;color: #FFFFFF;letter-spacing: 0.06em;">Privacy Policy</h3>
        </div>
    </div>
</section>
<section>
    <div class="container py-5">
    <div class="row text-white py-5">
    <p class="p-">
    Last updated: February 21, 2023
    </p>
    <p class="p-">
    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
    </p>
    <p class="p-">
    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 
    </p>

    <h2 class="h2-">
    Interpretation and Definitions
    </h2>

    <h2 class="h2-">
    Interpretation
    </h2>
    <p class="p-">
    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>

    <h2 class="h2-">
    Definitions
    </h2>
    <p class="p-">
    For the purposes of this Privacy Policy:
    </p>
    <p class="p-">
    <b> Account </b> means a unique account created for You to access our Service or parts of our Service.
    </p>
    <p class="p-">
    <b> Affiliate </b>  means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
    </p>
    <p class="p-">
    <b> Application </b> refers to Eventy, the software program provided by the Company.
    </p>
    <p class="p-">
    <b> Company </b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Eventy.
    </p>
    <p class="p-">
    <b> Country </b> refers to: Iraq
    </p>
    <p class="p-">
    <b> Device </b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
    </p>
    <p class="p-">
    <b> Personal Data </b> is any information that relates to an identified or identifiable individual.
    </p>
    <p class="p-">
    <b> Service </b> refers to the Application.
    </p>
    <p class="p-">
    <b> Service Provider </b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
    </p>
    <p class="p-">
    <b> Third-party Social Media Service </b> refers to any website or any social network website through which a User can log in or create an account to use the Service.
    </p>
    <p class="p-">
    <b> Usage Data </b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
    </p>
    <p class="p-">
    <b> You </b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
    </p>
    <p class="p-">
    Collecting and Using Your Personal Data
    </p>

    <h2 class="h2-">
    Types of Data Collected
    </h2>

    <h2 class="h2-">
    Personal Data
    </h2>
    <p class="p-">
    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
    </p>
    <p class="p-">
    Email address
    </p>
    <p class="p-">
    First name and last name
    </p>
    <p class="p-">
    Email address
    </p>
    <p class="p-">
    Phone number
    </p>
    <p class="p-">
    Address, State, Province, ZIP/Postal code, City
    </p>
    <p class="p-">
    Usage Data
    </p>

    <h2 class="h2-">
    Usage Data
    </h2>
    <p class="p-">
    Usage Data is collected automatically when using the Service.
    </p>
    <p class="p-">
    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
    </p>
    <p class="p-">
    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
    </p>
    <p class="p-">
    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
    </p>

    <h2 class="h2-">
    Information from Third-Party Social Media Services
    </h2>
    <p class="p-">
    The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
    </p>
    <p class="p-">
    ·         Google
    </p>
    <p class="p-">
    ·         Facebook
    </p>
    <p class="p-">
    ·         Twitter
    </p>
    <p class="p-">
    ·         LinkedIn
    </p>
    <p class="p-">
    If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
    </p>
    <p class="p-">
    You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
    </p>

    <h2 class="h2-">
    Information Collected while Using the Application
    </h2>
    <p class="p-">
    While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
    </p>
    <p class="p-">
    ·         Information regarding your location
    </p>
    <p class="p-">
    We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
    </p>
    <p class="p-">
    You can enable or disable access to this information at any time, through Your Device settings.
    </p>

    <h2 class="h2-">
    Use of Your Personal Data
    </h2>
    <p class="p-">
    The Company may use Personal Data for the following purposes:
    </p>
    <p class="p-">
    <b> To provide and maintain our Service,</b> including to monitor the usage of our Service.
    </p>
    <p class="p-">
    <b> To manage Your Account: </b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
    </p>
    <p class="p-">
    <b> For the performance of a contract:</b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
    </p>
    <p class="p-">
    <b> To contact You: </b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
    </p>
    <p class="p-">
    <b> To provide You </b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
    </p>
    <p class="p-">
    <b> To manage Your requests:</b> To attend and manage Your requests to Us.
    </p>
    <p class="p-">
    <b> For business transfers:</b> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
    </p>
    <p class="p-">
    <b> For other purposes:</b> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
    </p>
    <p class="p-">
    We may share Your personal information in the following situations:
    </p>
    <p class="p-">
    <b> ·         With Service Providers: </b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
    </p>
    <p class="p-">
    <b> ·         For business transfers: </b> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
    </p>
    <p class="p-">
    <b> ·         With Affiliates:</b> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
    </p>
    <p class="p-">
    <b> ·         With business partners: </b> We may share Your information with Our business partners to offer You certain products, services or promotions.
    </p>
    <p class="p-">
    <b> ·         With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.
    </p>
    <p class="p-">
    <b> ·         With Your consent: </b> We may disclose Your personal information for any other purpose with Your consent.
    </p>

    <h2 class="h2-">
    Retention of Your Personal Data
    </h2>
    <p class="p-">
    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
    </p>
    <p class="p-">
    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
    </p>

    <h2 class="h2-">
    Transfer of Your Personal Data
    </h2>
    <p class="p-">
    Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
    </p>
    <p class="p-">
    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
    </p>
    <p class="p-">
    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
    </p>

    <h2 class="h2-">
    Delete Your Personal Data
    </h2>
    <p class="p-">
    You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
    </p>
    <p class="p-">
    Our Service may give You the ability to delete certain information about You from within the Service.
    </p>
    <p class="p-">
    You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
    </p>
    <p class="p-">
    Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
    </p>

    <h2 class="h2-">
    Disclosure of Your Personal Data
    </h2>
    <h2 class="h2-">
    Business Transactions
    </h2>
    <p class="p-">
    If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
    </p>
    <h2 class="h2-">
    Law enforcement
    </h2>
    <p class="p-">
    Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
       </p>
    <h2 class="h2-">
    Other legal requirements
    </h2>
    <p class="p-">
    The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
       </p>
    <p class="p-">
    ·         Comply with a legal obligation
       </p>
    <p class="p-">
    ·         Protect and defend the rights or property of the Company
       </p>
    <p class="p-">
    ·         Prevent or investigate possible wrongdoing in connection with the Service
       </p>
    <p class="p-">
    ·         Protect the personal safety of Users of the Service or the public
       </p>
    <p class="p-">
    ·         Protect against legal liability
       </p>

       <h2 class="h2-">
       Security of Your Personal Data
    </h2>
    <p class="p-">
    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
    </p>
    <p class="p-">
    Children's Privacy
    </p>
    <p class="p-">
    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
    </p>
    <p class="p-">
    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
    </p>
    <p class="p-">
    Links to Other Websites
    </p>
    <p class="p-">
    Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
    </p>
    <p class="p-">
    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
    </p>
    <p class="p-">
    Changes to this Privacy Policy
    </p>
    <p class="p-">
    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
    </p>
    <p class="p-">
    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
    </p>
    <p class="p-">
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
    </p>
    <p class="p-">
    Contact Us
    </p>
    <p class="p-">
    If you have any questions about this Privacy Policy, You can contact us:
    </p>
    <p class="p-">
    By email: info@eventy.krd
    </p>
    <p class="p-">
    By visiting this page on our website: https://www.eventy.krd/contact
    </p>
    <p class="p-">
    By WhatsApp Number:: +964 750 953 5159
    </p>

    <h2 class="py-4" style="font-family: 'Montserrat';font-style: normal;font-weight: 700;font-size: 25px;line-height: 30px;color: #FFFFFF;">
    Contact Us
    </h2>
    <p style="font-family: 'Montserrat';font-style: normal;font-weight: 500;font-size: 18px;line-height: 150%;color: #FFFFFF;">
    If you have any questions about these Terms, please contact us:
    </p>
    <div class="pt-4">
                      
                      <span class="mx-1">
                         <a class="text-decoration-none" aria-current="page" href="https://www.facebook.com/Eventykrd-100446199635053/"  target="_blank">
                         <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                         <path d="M0 15C0 6.71573 6.71573 0 15 0H20C28.2843 0 35 6.71573 35 15V20C35 28.2843 28.2843 35 20 35H15C6.71573 35 0 28.2843 0 20V15Z" fill="#DDD9FB"/>
                         <path d="M22 15.5H19V13.5C19 13.2348 19.1054 12.9804 19.2929 12.7929C19.4804 12.6054 19.7348 12.5 20 12.5H21V10H19C18.2044 10 17.4413 10.3161 16.8787 10.8787C16.3161 11.4413 16 12.2044 16 13V15.5H14V18H16V25H19V18H21L22 15.5Z" stroke="#7E6EF6" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                         </svg>
       
                         </a>
                      </span>
                      <span class="mx-1">
                         <a class="text-decoration-none"  href="https://www.instagram.com/eventy.krd/">
                         <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"  target="_blank">
                         <path d="M0 15C0 6.71573 6.71573 0 15 0H20C28.2843 0 35 6.71573 35 15V20C35 28.2843 28.2843 35 20 35H15C6.71573 35 0 28.2843 0 20V15Z" fill="#DDD9FB"/>
                         <path d="M21.185 11H14.5963C12.6101 11 11 12.6101 11 14.5963V21.185C11 23.1712 12.6101 24.7812 14.5963 24.7812H21.185C23.1712 24.7812 24.7812 23.1712 24.7812 21.185V14.5963C24.7812 12.6101 23.1712 11 21.185 11Z" stroke="#7E6EF6" stroke-linecap="round" stroke-linejoin="round"/>
                         <path d="M17.8906 21.5C19.884 21.5 21.5 19.884 21.5 17.8906C21.5 15.8972 19.884 14.2812 17.8906 14.2812C15.8972 14.2812 14.2812 15.8972 14.2812 17.8906C14.2812 19.884 15.8972 21.5 17.8906 21.5Z" stroke="#7E6EF6" stroke-linecap="round" stroke-linejoin="round"/>
                         <path d="M21.8281 13.625C22.0093 13.625 22.1562 13.4781 22.1562 13.2969C22.1562 13.1157 22.0093 12.9688 21.8281 12.9688C21.6469 12.9688 21.5 13.1157 21.5 13.2969C21.5 13.4781 21.6469 13.625 21.8281 13.625Z" stroke="#7E6EF6" stroke-linecap="round" stroke-linejoin="round"/>
                         </svg>
                         </a>
                      </span>
                      <span class="mx-1">
                         <a class="text-decoration-none"  href="mailto:info@eventy.krd">
                         <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                         <path d="M0 15C0 6.71573 6.71573 0 15 0H20C28.2843 0 35 6.71573 35 15V20C35 28.2843 28.2843 35 20 35H15C6.71573 35 0 28.2843 0 20V15Z" fill="#DDD9FB"/>
                         <path d="M24.625 12H10.375C10.1687 12 10 12.1687 10 12.375V21.75C10 21.9563 10.1687 22.125 10.375 22.125H24.625C24.8313 22.125 25 21.9563 25 21.75V12.375C25 12.1687 24.8313 12 24.625 12ZM23.725 12.75L17.5 18.975L11.275 12.75H23.725ZM10.75 13.275L14.5375 17.0625L10.75 20.85V13.275ZM11.2937 21.375L15.0625 17.6063L17.2375 19.7812C17.3875 19.9313 17.6125 19.9313 17.7625 19.7812L19.9375 17.6063L23.7062 21.375H11.2937ZM24.25 20.85L20.4625 17.0625L24.25 13.275V20.85Z" fill="#7E6EF6"/>
                         </svg>
       
                         </a>
                      </span>
                      <span class="mx-1">
                         <a class="text-decoration-none"  href="tel:009647507680176">
                         <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
                         <path d="M0 15C0 6.71573 6.71573 0 15 0H20C28.2843 0 35 6.71573 35 15V20C35 28.2843 28.2843 35 20 35H15C6.71573 35 0 28.2843 0 20V15Z" fill="#DDD9FB"/>
                         <path d="M13.426 11.2452C13.3706 11.174 13.3008 11.1154 13.221 11.0733C13.1413 11.0312 13.0535 11.0065 12.9635 11.001C12.8735 10.9954 12.7834 11.009 12.699 11.0409C12.6147 11.0729 12.5381 11.1224 12.4744 11.1862L11.5051 12.1565C11.0523 12.6102 10.8854 13.2524 11.0832 13.8158C11.9042 16.1478 13.2397 18.2651 14.9906 20.0106C16.7361 21.7615 18.8534 23.097 21.1854 23.918C21.7488 24.1158 22.391 23.9489 22.8447 23.4961L23.8141 22.5268C23.8779 22.463 23.9274 22.3865 23.9593 22.3021C23.9913 22.2178 24.0049 22.1277 23.9993 22.0377C23.9937 21.9477 23.969 21.8599 23.9269 21.7802C23.8848 21.7004 23.8262 21.6306 23.755 21.5752L21.5923 19.8934C21.5162 19.8344 21.4277 19.7935 21.3336 19.7737C21.2394 19.7538 21.1419 19.7557 21.0485 19.779L18.9955 20.2918C18.7214 20.3603 18.4343 20.3567 18.1621 20.2813C17.8899 20.2059 17.6418 20.0613 17.4421 19.8615L15.1397 17.5582C14.9398 17.3585 14.795 17.1105 14.7194 16.8383C14.6438 16.5661 14.64 16.2789 14.7084 16.0048L15.2222 13.9517C15.2455 13.8583 15.2473 13.7609 15.2275 13.6667C15.2077 13.5725 15.1668 13.484 15.1078 13.408L13.426 11.2452ZM11.7666 10.4793C11.9307 10.3152 12.1278 10.1879 12.3448 10.1058C12.5618 10.0237 12.7939 9.98872 13.0255 10.0032C13.257 10.0176 13.4829 10.0812 13.6881 10.1896C13.8932 10.2981 14.0729 10.4489 14.2153 10.6321L15.8971 12.7939C16.2056 13.1905 16.3143 13.707 16.1924 14.1945L15.6796 16.2476C15.6531 16.3539 15.6546 16.4653 15.6838 16.5709C15.713 16.6765 15.7691 16.7728 15.8465 16.8504L18.1499 19.1537C18.2275 19.2313 18.324 19.2875 18.4298 19.3167C18.5356 19.3459 18.6471 19.3473 18.7536 19.3206L20.8057 18.8078C21.0463 18.7477 21.2974 18.743 21.54 18.7942C21.7827 18.8453 22.0105 18.951 22.2063 19.1031L24.3681 20.7849C25.1453 21.3896 25.2165 22.538 24.5209 23.2327L23.5516 24.202C22.8579 24.8957 21.821 25.2004 20.8545 24.8601C18.3807 23.9897 16.1346 22.5735 14.2828 20.7165C12.4259 18.865 11.0097 16.6192 10.1392 14.1458C9.79982 13.1802 10.1045 12.1424 10.7982 11.4487L11.7676 10.4793H11.7666Z" fill="#7E6EF6"/>
                         </svg>
       
                         </a>
                      </span>
                      <span class="mx-1">
                         <a class="text-decoration-none"  href="https://eventy.krd/">
                         <svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"  target="_blank">
                         <path d="M0 15C0 6.71573 6.71573 0 15 0H20C28.2843 0 35 6.71573 35 15V20C35 28.2843 28.2843 35 20 35H15C6.71573 35 0 28.2843 0 20V15Z" fill="#DDD9FB"/>
                         <path d="M18 10C15.8783 10 13.8434 10.8429 12.3431 12.3431C10.8429 13.8434 10 15.8783 10 18C10 20.1217 10.8429 22.1566 12.3431 23.6569C13.8434 25.1571 15.8783 26 18 26C20.1217 26 22.1566 25.1571 23.6569 23.6569C25.1571 22.1566 26 20.1217 26 18C26 15.8783 25.1571 13.8434 23.6569 12.3431C22.1566 10.8429 20.1217 10 18 10ZM10.9867 18.6044H13.2178C13.2533 19.4133 13.3662 20.2169 13.5556 21.0044H11.6356C11.2775 20.2497 11.0577 19.4368 10.9867 18.6044ZM18.6044 13.8044V11.0578C19.4611 11.3833 20.1649 12.0174 20.5778 12.8356C20.76 13.144 20.9209 13.4649 21.0578 13.7956L18.6044 13.8044ZM21.4667 15.0044C21.6729 15.7893 21.7956 16.5938 21.8311 17.4044H18.6044V15.0044H21.4667ZM17.3956 11.0578V13.8044H14.9422C15.0793 13.4735 15.2397 13.1527 15.4222 12.8444C15.8333 12.023 16.5374 11.3855 17.3956 11.0578ZM17.3956 15.0044V17.4044H14.1778C14.2133 16.5938 14.336 15.7893 14.5422 15.0044H17.3956ZM13.2178 17.3956H10.9867C11.0577 16.5632 11.2775 15.7503 11.6356 14.9956H13.5556C13.3659 15.7828 13.2527 16.5865 13.2178 17.3956ZM14.1778 18.6044H17.3956V21.0044H14.5422C14.336 20.2196 14.2139 19.4151 14.1778 18.6044ZM17.4044 22.16V24.9067C16.5478 24.5811 15.844 23.947 15.4311 23.1289C15.2486 22.8206 15.0882 22.4998 14.9511 22.1689L17.4044 22.16ZM18.6044 24.9067V22.2044H21.0578C20.9207 22.5354 20.7603 22.8562 20.5778 23.1644C20.1649 23.9826 19.4611 24.6167 18.6044 24.9422V24.9067ZM18.6044 20.96V18.56H21.8222C21.7861 19.3707 21.664 20.1752 21.4578 20.96H18.6044ZM22.7911 18.56H25.0222C24.9511 19.3924 24.7314 20.2052 24.3733 20.96H22.4444C22.6311 20.1867 22.744 19.3982 22.7822 18.6044L22.7911 18.56ZM22.7911 17.36C22.7504 16.5656 22.6343 15.7769 22.4444 15.0044H24.3644C24.7227 15.76 24.9422 16.5724 25.0133 17.4044L22.7911 17.36ZM23.68 13.8044H22.0889C21.801 12.9958 21.3837 12.2393 20.8533 11.5644C21.9595 12.061 22.9202 12.832 23.6444 13.8044H23.68ZM15.1467 11.5644C14.6163 12.2393 14.199 12.9958 13.9111 13.8044H12.3556C13.0798 12.832 14.0405 12.061 15.1467 11.5644ZM12.3467 22.2311H13.9111C14.199 23.0397 14.6163 23.7962 15.1467 24.4711C14.0375 23.9671 13.0764 23.1866 12.3556 22.2044L12.3467 22.2311ZM20.8444 24.4711C21.3748 23.7962 21.7921 23.0397 22.08 22.2311H23.6444C22.9158 23.1905 21.9554 23.949 20.8533 24.4356L20.8444 24.4711Z" fill="#7E6EF6"/>
                         </svg>
       
                         </a>
                      </span>
         
                </div>
    </div>
    </div>
</section>
@include('components.download')
</div>
@endsection